; AUTOGENERATED by tools/gen_iso.py

MAPW equ 8
MAPH equ 8
MAPD equ 6

level1_map:
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,001h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,003h,003h,000h,000h,000h,000h,000h
        db 000h,004h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,002h,002h,002h,000h,000h
        db 000h,000h,000h,000h,004h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,001h,001h,003h,000h,000h,000h
        db 000h,000h,000h,004h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h

keys_tab:
        db 3,4,3,12,11
        db 4,2,3,18,10
        db 1,0,4,16,2

slab_tab:
        db 89,89,128,24,14
        db 73,81,112,24,11
        db 137,81,112,24,4
        db 57,73,96,24,11
        db 121,73,96,24,4
        db 185,81,96,16,7
        db 105,65,80,24,4
        db 121,33,32,32,14
        db 105,25,16,32,14

cover_tab:
        db 020h,020h,020h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h

keys_gfx:
        db 003h,040h,01Eh,033h,0A1h,021h,0B3h,09Eh,0C0h,010h,011h,060h,040h,011h,014h,000h
        db 007h,0F6h,0E0h,060h,080h,000h,000h,000h,0FEh,036h,0B6h,080h,000h,000h,000h,000h
        db 021h,061h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,021h,061h,061h,061h,061h,061h,061h,0F1h
        db 0F1h,0B1h,0B1h,0FBh,0FBh,0FBh,0FBh,0FBh,0F1h,0F1h,0F1h,0B1h,0FBh,0FBh,0FBh,0FBh
        db 000h,000h,01Eh,033h,021h,021h,0B3h,09Eh,000h,000h,000h,000h,001h,000h,00Bh,000h
        db 007h,0F6h,0E0h,081h,007h,0E0h,080h,000h,0FEh,036h,0B6h,080h,001h,007h,0E0h,081h
        db 0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,061h,0F1h,061h,0F1h
        db 0F1h,041h,041h,047h,047h,074h,074h,0F4h,0F1h,0F1h,0F1h,041h,074h,074h,047h,047h
        db 00Ah,000h,000h,000h,07Fh,000h,09Eh,033h,00Ch,0F3h,0E3h,0E4h,0E7h,0E7h,067h,077h
        db 021h,021h,033h,01Eh,007h,0B6h,0B0h,05Fh,07Fh,00Fh,003h,000h,0FEh,036h,0B6h,080h
        db 086h,0F6h,0F6h,0F6h,061h,0F1h,0F1h,0F1h,086h,061h,061h,061h,061h,061h,061h,061h
        db 0F1h,0F1h,0F1h,0F1h,0F1h,061h,061h,061h,061h,061h,061h,0F1h,0F1h,0F1h,0F1h,061h

exit_gfx_0:
        db 000h,00Eh,040h,020h,060h,006h,05Fh,07Fh,0BFh,006h,05Fh,080h,041h,008h,01Ch,080h
        db 0C0h,0C0h,01Ch,080h,0C1h,008h,01Ch,080h,000h,000h,000h,03Fh,0C0h,0C0h,01Ch,080h
        db 001h,038h,013h,084h,01Eh,078h,01Eh,078h,0C1h,008h,01Ch,080h,001h,038h,013h,084h
        db 0C1h,008h,01Ch,080h,0C0h,00Eh,018h,090h,0C0h,00Eh,018h,090h,043h,00Fh,03Ch,00Fh
        db 0F6h,061h,061h,061h,061h,0F1h,0F1h,0F1h,061h,0F1h,0F1h,06Fh,07Fh,0F7h,0F7h,07Fh
        db 0F6h,071h,0F7h,07Fh,07Fh,0F7h,0F7h,07Fh,0F6h,0F6h,0F6h,061h,0F6h,076h,0F7h,07Fh
        db 07Fh,0F7h,074h,047h,047h,047h,074h,074h,07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,074h,047h
        db 07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,0F7h,074h,07Fh,0F7h,0F7h,074h,047h,074h,047h,047h
exit_gfx_1:
        db 000h,00Eh,040h,020h,060h,006h,05Fh,07Fh,0BFh,006h,05Fh,080h,041h,008h,01Ch,080h
        db 0C0h,0C0h,01Ch,080h,0C1h,008h,01Ch,080h,000h,000h,000h,03Fh,0C0h,0C0h,01Ch,080h
        db 001h,007h,01Ch,084h,01Eh,078h,01Eh,078h,0C1h,008h,01Ch,080h,001h,007h,01Ch,084h
        db 0C1h,008h,01Ch,080h,0C0h,00Fh,0E0h,070h,0C0h,00Fh,0E0h,070h,043h,00Fh,03Ch,00Fh
        db 0F6h,061h,061h,061h,061h,071h,071h,071h,061h,071h,071h,067h,0F7h,07Fh,07Fh,0F7h
        db 076h,0F1h,07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,0F6h,0F6h,0F6h,061h,076h,0F6h,07Fh,0F7h
        db 0F7h,0F7h,074h,047h,047h,047h,074h,074h,0F7h,07Fh,07Fh,0F7h,0F7h,0F7h,074h,047h
        db 0F7h,07Fh,07Fh,0F7h,0F7h,07Fh,0F7h,074h,0F7h,07Fh,0F7h,074h,047h,074h,047h,047h

hazards_tab:
        db 1,2,18
        db 5,1,18
        db 2,4,34

; crumb_tab (18B): ncells, (bx,y,bz)x2 FF-pad, c0,r0,c1,r1,
;   dw rectsize, dw dataaddr(8000h-based), per-cell slab idx x2
crumb_tab:
        db 2,1,3,0,2,3,0,15,5,22,11
        dw 672, 32768
        db 8,7
        db 1,4,2,4,255,255,255,13,13,18,17
        dw 320, 38816
        db 0,255

level2_map:
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,001h,000h,000h,000h,000h,000h
        db 000h,000h,004h,003h,004h,000h,000h,000h
        db 000h,000h,000h,000h,003h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,001h,000h,000h,000h
        db 000h,000h,000h,000h,004h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h

keys_tab2:
        db 2,2,2,14,9
        db 4,4,3,14,12
        db 4,2,2,18,9

slab_tab2:
        db 153,113,160,16,7
        db 137,105,144,16,15
        db 89,89,128,24,15
        db 121,65,96,32,7
        db 105,65,80,24,7
        db 89,65,64,16,15

cover_tab2:
        db 000h,000h,000h,020h,000h,000h,000h,000h
        db 000h,000h,020h,020h,020h,000h,000h,000h
        db 000h,000h,000h,020h,020h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h

keys_gfx2:
        db 038h,0FCh,028h,050h,060h,003h,0A0h,0F9h,08Ch,00Dh,0E7h,007h,003h,007h,005h,007h
        db 058h,006h,018h,060h,080h,0FFh,0FFh,0FFh,0CFh,005h,00Ch,01Ch,0FFh,001h,007h,0E0h
        db 05Fh,0F1h,05Fh,05Fh,05Fh,02Fh,05Fh,0F1h,05Fh,0F1h,021h,0F2h,0F2h,0F2h,052h,0F2h
        db 0F5h,07Fh,07Fh,07Fh,07Fh,0FFh,0FFh,0FFh,0F1h,05Fh,07Fh,0F1h,0FFh,07Fh,07Fh,0F7h
        db 037h,0F8h,0F9h,003h,038h,0C0h,0F3h,0F9h,03Eh,009h,0E3h,0F4h,0F2h,0F0h,0F0h,0E0h
        db 04Ch,006h,060h,060h,080h,0FFh,0FFh,0FFh,0C0h,0C0h,0DCh,01Ch,0FFh,0FFh,0FFh,0FFh
        db 051h,051h,051h,025h,051h,051h,051h,0F1h,051h,051h,021h,021h,021h,021h,021h,021h
        db 05Fh,07Fh,05Fh,07Fh,07Fh,0FFh,0FFh,0FFh,0F1h,0F1h,0F1h,0F1h,0FFh,0FFh,0FFh,0FFh
        db 0FFh,001h,002h,0FFh,001h,0FCh,050h,0A0h,080h,070h,003h,058h,050h,00Ch,0E7h,007h
        db 003h,003h,0A0h,018h,0FCh,0FEh,0FEh,0FEh,007h,007h,007h,0E7h,0C0h,0C0h,0C0h,01Fh
        db 0FFh,05Fh,05Fh,0FFh,05Fh,0F1h,0F5h,05Fh,057h,0F7h,07Fh,05Fh,05Fh,051h,021h,0F2h
        db 02Fh,02Fh,05Fh,07Fh,071h,071h,071h,071h,0F2h,0F2h,0F2h,021h,0F7h,0F7h,0F7h,071h

exit_gfx2_0:
        db 0FFh,0FFh,0FFh,0FFh,0FFh,001h,003h,0FFh,0FFh,001h,003h,0FFh,041h,008h,01Ch,080h
        db 00Dh,0C0h,0E0h,080h,0C1h,008h,01Ch,080h,084h,0C1h,008h,082h,002h,0C0h,0E0h,080h
        db 001h,038h,013h,084h,01Eh,078h,01Eh,078h,0C1h,008h,01Ch,080h,001h,038h,013h,084h
        db 0C1h,008h,01Ch,080h,0C0h,00Eh,018h,090h,0C0h,00Eh,018h,090h,043h,00Fh,03Ch,00Fh
        db 0FFh,0FFh,0FFh,0FFh,0FFh,07Fh,07Fh,0FFh,0FFh,07Fh,07Fh,0FFh,07Fh,0F7h,0F7h,07Fh
        db 05Fh,07Fh,07Fh,07Fh,07Fh,0F7h,0F7h,07Fh,05Fh,0F5h,05Fh,05Fh,05Fh,07Fh,07Fh,07Fh
        db 07Fh,0F7h,074h,047h,047h,047h,074h,074h,07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,074h,047h
        db 07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,0F7h,074h,07Fh,0F7h,0F7h,074h,047h,074h,047h,047h
exit_gfx2_1:
        db 0FFh,0FFh,0FFh,0FFh,001h,006h,01Ch,080h,001h,006h,01Ch,080h,041h,008h,01Ch,080h
        db 00Dh,030h,01Ch,080h,0C1h,008h,01Ch,080h,084h,0C1h,008h,082h,0C0h,030h,01Ch,080h
        db 001h,007h,01Ch,084h,01Eh,078h,01Eh,078h,0C1h,008h,01Ch,080h,001h,007h,01Ch,084h
        db 0C1h,008h,01Ch,080h,0C0h,00Fh,0E0h,070h,0C0h,00Fh,0E0h,070h,043h,00Fh,03Ch,00Fh
        db 0FFh,0FFh,0FFh,0FFh,07Fh,07Fh,07Fh,0F7h,07Fh,07Fh,07Fh,0F7h,0F7h,07Fh,07Fh,0F7h
        db 05Fh,07Fh,07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,05Fh,0F5h,05Fh,05Fh,07Fh,07Fh,07Fh,0F7h
        db 0F7h,0F7h,074h,047h,047h,047h,074h,074h,0F7h,07Fh,07Fh,0F7h,0F7h,0F7h,074h,047h
        db 0F7h,07Fh,07Fh,0F7h,0F7h,07Fh,0F7h,074h,0F7h,07Fh,0F7h,074h,047h,074h,047h,047h

hazards_tab2:
        db 3,5,18
        db 5,1,18

; crumb_tab2 (18B): ncells, (bx,y,bz)x2 FF-pad, c0,r0,c1,r1,
;   dw rectsize, dw dataaddr(8000h-based), per-cell slab idx x2
crumb_tab2:
        db 1,3,2,2,255,255,255,15,10,19,14
        dw 256, 32768
        db 4,255
        db 1,4,3,2,255,255,255,17,10,22,15
        dw 400, 33536
        db 3,255

level3_map:
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,001h,000h
        db 000h,000h,000h,000h,000h,000h,004h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,003h,003h,003h,000h,000h
        db 000h,000h,000h,004h,000h,004h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,001h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h

keys_tab3:
        db 3,2,4,16,8
        db 5,2,4,20,10
        db 6,1,2,24,12

slab_tab3:
        db 121,113,160,16,7
        db 137,73,112,32,10
        db 169,89,112,16,11
        db 121,65,96,32,10
        db 105,57,80,32,10

cover_tab3:
        db 000h,000h,020h,020h,020h,000h,000h,000h
        db 000h,020h,020h,020h,020h,020h,000h,000h
        db 000h,000h,020h,020h,020h,020h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h

keys_gfx3:
        db 0D0h,080h,09Eh,0B3h,021h,021h,0B3h,09Eh,0FCh,00Ch,07Ch,04Ch,07Fh,01Ah,060h,000h
        db 007h,050h,060h,060h,080h,000h,000h,000h,0FEh,036h,0B6h,080h,000h,000h,000h,000h
        db 06Ah,0A1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,061h,06Ah,0A1h,06Ah,0A1h,06Ah,06Ah,0F1h
        db 0F1h,0A6h,0A1h,0FAh,0FAh,0FAh,0FAh,0FAh,0F1h,0F1h,0F1h,0A1h,0FAh,0FAh,0FAh,0FAh
        db 020h,080h,09Eh,0B3h,0A1h,021h,0B3h,09Eh,040h,0D0h,028h,044h,029h,07Fh,00Ch,000h
        db 007h,0F6h,0E0h,060h,080h,000h,000h,000h,0FEh,036h,0B6h,080h,000h,000h,000h,000h
        db 06Ah,061h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0A6h,0A6h,0A6h,06Ah,06Ah,0A1h,06Ah,0F1h
        db 0F1h,0A1h,0A1h,0FAh,0FAh,0FAh,0FAh,0FAh,0F1h,0F1h,0F1h,0A1h,0FAh,0FAh,0FAh,0FAh
        db 05Ch,0C0h,09Eh,0B3h,021h,021h,0B3h,09Eh,000h,00Fh,043h,07Fh,060h,07Fh,041h,000h
        db 007h,0F6h,0C0h,060h,080h,000h,000h,000h,0FEh,036h,0B6h,080h,000h,000h,000h,000h
        db 0A6h,0A1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F6h,06Ah,06Ah,0A1h,06Ah,0A1h,06Ah,0F1h
        db 0F1h,0A1h,0A1h,0FBh,0FBh,0FBh,0FBh,0FBh,0F1h,0F1h,0F1h,0B1h,0FBh,0FBh,0FBh,0FBh

exit_gfx3_0:
        db 08Ch,000h,002h,084h,004h,002h,008h,092h,012h,006h,03Fh,080h,0BFh,080h,023h,03Fh
        db 0C0h,030h,01Ch,080h,0C1h,008h,01Ch,080h,01Ch,038h,000h,024h,0C0h,0C0h,01Ch,080h
        db 080h,008h,042h,006h,048h,009h,045h,000h,000h,038h,013h,084h,01Eh,078h,01Eh,078h
        db 0C1h,008h,01Ch,080h,001h,038h,013h,084h,0C1h,008h,01Ch,080h,0C0h,00Eh,018h,090h
        db 0C0h,00Eh,018h,090h,043h,00Fh,03Ch,00Fh,080h,080h,00Ah,015h,031h,00Ah,014h,080h
        db 06Ah,0F1h,0FDh,0FDh,0FDh,0FDh,0FDh,0FDh,06Ah,0FAh,0F1h,0DFh,0F1h,0D7h,07Fh,0F1h
        db 0FAh,0F7h,0F7h,07Fh,07Fh,0F7h,0F7h,07Fh,06Ah,06Ah,0FAh,06Ah,0FAh,07Ah,0F7h,07Fh
        db 06Ah,06Ah,06Ah,06Ah,06Ah,06Ah,06Ah,0FAh,0F1h,0F7h,074h,047h,047h,047h,074h,074h
        db 07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,074h,047h,07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,0F7h,074h
        db 07Fh,0F7h,0F7h,074h,047h,074h,047h,047h,0FAh,04Ah,06Ah,06Ah,06Ah,06Ah,06Ah,07Ah
exit_gfx3_1:
        db 08Ch,000h,002h,084h,004h,002h,008h,092h,012h,006h,03Fh,080h,081h,080h,01Ch,03Fh
        db 0C0h,030h,01Ch,080h,0C1h,008h,01Ch,080h,01Ch,038h,000h,024h,0C0h,0C0h,01Ch,080h
        db 080h,008h,042h,006h,048h,009h,045h,000h,000h,007h,01Ch,084h,01Eh,078h,01Eh,078h
        db 0C1h,008h,01Ch,080h,001h,007h,01Ch,084h,0C1h,008h,01Ch,080h,0C0h,00Fh,0E0h,070h
        db 0C0h,00Fh,0E0h,070h,043h,00Fh,03Ch,00Fh,080h,080h,00Ah,015h,031h,00Ah,014h,080h
        db 06Ah,0F1h,0FDh,0FDh,0FDh,0FDh,0FDh,0FDh,06Ah,07Ah,071h,0D7h,0F7h,0DFh,07Fh,071h
        db 07Ah,07Fh,07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,06Ah,06Ah,0FAh,06Ah,07Ah,0FAh,07Fh,0F7h
        db 06Ah,06Ah,06Ah,06Ah,06Ah,06Ah,06Ah,0FAh,0F1h,0F7h,074h,047h,047h,047h,074h,074h
        db 0F7h,07Fh,07Fh,0F7h,0F7h,0F7h,074h,047h,0F7h,07Fh,07Fh,0F7h,0F7h,07Fh,0F7h,074h
        db 0F7h,07Fh,0F7h,074h,047h,074h,047h,047h,07Ah,04Ah,06Ah,06Ah,06Ah,06Ah,06Ah,07Ah

hazards_tab3:
        db 2,3,18
        db 5,4,18

; crumb_tab3 (18B): ncells, (bx,y,bz)x2 FF-pad, c0,r0,c1,r1,
;   dw rectsize, dw dataaddr(8000h-based), per-cell slab idx x2
crumb_tab3:
        db 1,3,3,2,255,255,255,15,9,19,14
        dw 320, 32768
        db 4,255
        db 1,4,3,2,255,255,255,17,10,21,15
        dw 320, 33728
        db 3,255
        db 1,5,3,2,255,255,255,19,11,24,16
        dw 400, 34688
        db 1,255

level4_map:
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,001h,000h
        db 000h,000h,000h,000h,000h,000h,004h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,001h,000h,001h,000h,000h
        db 000h,000h,000h,004h,000h,004h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,001h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 001h,001h,001h,001h,001h,001h,001h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h

keys_tab4:
        db 3,2,4,16,8
        db 5,2,4,20,10
        db 6,1,2,24,12

slab_tab4:
        db 121,113,160,16,7
        db 137,73,112,32,13
        db 169,89,112,16,13
        db 105,57,80,32,13

cover_tab4:
        db 000h,000h,020h,000h,020h,000h,000h,000h
        db 000h,020h,020h,020h,020h,020h,000h,000h
        db 000h,000h,020h,020h,020h,020h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h

keys_gfx4:
        db 001h,000h,01Eh,033h,021h,021h,033h,01Eh,0C0h,03Fh,00Ch,003h,000h,000h,000h,000h
        db 007h,006h,010h,060h,080h,000h,000h,000h,0FEh,036h,0B6h,080h,000h,000h,000h,000h
        db 081h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,084h,041h,081h,081h,0F1h,0F1h,0F1h,0F1h
        db 0F1h,0F1h,0F1h,0FDh,0FDh,0FDh,0FDh,0FDh,0F1h,0F1h,0F1h,0D1h,0FDh,0FDh,0FDh,0FDh
        db 001h,000h,01Eh,033h,021h,021h,033h,01Eh,0C0h,03Fh,00Ch,003h,000h,000h,000h,000h
        db 007h,006h,010h,060h,080h,000h,000h,000h,0FEh,036h,0B6h,080h,000h,000h,000h,000h
        db 081h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,084h,041h,081h,081h,0F1h,0F1h,0F1h,0F1h
        db 0F1h,0F1h,0F1h,0FDh,0FDh,0FDh,0FDh,0FDh,0F1h,0F1h,0F1h,0D1h,0FDh,0FDh,0FDh,0FDh
        db 001h,000h,01Eh,033h,021h,021h,033h,01Eh,0C0h,03Fh,00Ch,003h,000h,000h,000h,000h
        db 007h,006h,010h,060h,080h,000h,000h,000h,0FEh,036h,0B6h,080h,000h,000h,000h,000h
        db 081h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,084h,041h,081h,081h,0F1h,0F1h,0F1h,0F1h
        db 0F1h,0F1h,0F1h,0FDh,0FDh,0FDh,0FDh,0FDh,0F1h,0F1h,0F1h,0D1h,0FDh,0FDh,0FDh,0FDh

exit_gfx4_0:
        db 0C0h,030h,00Ch,003h,001h,006h,01Ch,07Fh,001h,006h,01Ch,07Fh,041h,008h,01Ch,080h
        db 0C0h,0C0h,01Ch,080h,0C1h,008h,01Ch,080h,001h,006h,018h,060h,0C0h,0C0h,01Ch,080h
        db 0C0h,030h,00Ch,003h,000h,000h,000h,000h,001h,038h,013h,084h,01Eh,078h,01Eh,078h
        db 0C1h,008h,01Ch,080h,001h,038h,013h,084h,0C1h,008h,01Ch,080h,0C0h,00Eh,018h,090h
        db 0C0h,00Eh,018h,090h,043h,00Fh,03Ch,00Fh,080h,080h,080h,080h,080h,006h,018h,060h
        db 081h,081h,081h,081h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,0F1h,07Fh,0F7h,0F7h,07Fh
        db 0F1h,071h,0F7h,07Fh,07Fh,0F7h,0F7h,07Fh,081h,081h,081h,081h,0F1h,071h,0F7h,07Fh
        db 081h,081h,081h,081h,0F1h,0F1h,0F1h,0F1h,07Fh,0F7h,074h,047h,047h,047h,074h,074h
        db 07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,074h,047h,07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,0F7h,074h
        db 07Fh,0F7h,0F7h,074h,047h,074h,047h,047h,0F1h,041h,071h,071h,041h,081h,081h,081h
exit_gfx4_1:
        db 0C0h,030h,00Ch,003h,001h,006h,01Ch,07Fh,001h,006h,01Ch,07Fh,041h,008h,01Ch,080h
        db 0C0h,0C0h,01Ch,080h,0C1h,008h,01Ch,080h,001h,006h,018h,060h,0C0h,0C0h,01Ch,080h
        db 0C0h,030h,00Ch,003h,000h,000h,000h,000h,001h,007h,01Ch,084h,01Eh,078h,01Eh,078h
        db 0C1h,008h,01Ch,080h,001h,007h,01Ch,084h,0C1h,008h,01Ch,080h,0C0h,00Fh,0E0h,070h
        db 0C0h,00Fh,0E0h,070h,043h,00Fh,03Ch,00Fh,080h,080h,080h,080h,080h,006h,018h,060h
        db 081h,081h,081h,081h,071h,071h,071h,071h,071h,071h,071h,071h,0F7h,07Fh,07Fh,0F7h
        db 071h,0F1h,07Fh,0F7h,0F7h,07Fh,07Fh,0F7h,081h,081h,081h,081h,071h,0F1h,07Fh,0F7h
        db 081h,081h,081h,081h,0F1h,0F1h,0F1h,0F1h,0F7h,0F7h,074h,047h,047h,047h,074h,074h
        db 0F7h,07Fh,07Fh,0F7h,0F7h,0F7h,074h,047h,0F7h,07Fh,07Fh,0F7h,0F7h,07Fh,0F7h,074h
        db 0F7h,07Fh,0F7h,074h,047h,074h,047h,047h,071h,041h,071h,071h,041h,081h,081h,081h

hazards_tab4:
        db 1,2,18
        db 3,4,18

; crumb_tab4 (18B): ncells, (bx,y,bz)x2 FF-pad, c0,r0,c1,r1,
;   dw rectsize, dw dataaddr(8000h-based), per-cell slab idx x2
crumb_tab4:

; redefined font, 76 chars from '0' (8 bytes each)
fonts_tab:
        db 00Eh,019h,031h,031h,031h,033h,03Fh,01Eh,006h,00Eh,03Ch,00Ch,008h,018h,038h,038h
        db 01Ch,036h,022h,006h,00Ch,031h,07Eh,07Ch,01Ch,036h,022h,00Ch,002h,046h,07Ch,038h
        db 00Ch,00Ch,01Ah,012h,064h,07Fh,01Eh,038h,026h,01Fh,010h,03Eh,033h,003h,07Eh,038h
        db 00Eh,018h,030h,03Ch,066h,046h,07Ch,038h,042h,07Fh,033h,004h,00Ch,018h,038h,038h
        db 01Ch,03Fh,026h,018h,024h,066h,07Eh,03Ch,03Ch,067h,067h,03Eh,00Ch,018h,038h,038h
        db 000h,000h,020h,000h,000h,020h,000h,000h,000h,000h,020h,000h,000h,020h,020h,040h
        db 018h,030h,060h,0C0h,060h,030h,018h,000h,000h,000h,0F8h,000h,0F8h,000h,000h,000h
        db 0C0h,060h,030h,018h,030h,060h,0C0h,000h,070h,088h,008h,010h,020h,000h,020h,000h
        db 070h,088h,008h,068h,0A8h,0A8h,070h,000h,002h,006h,006h,04Ah,073h,03Bh,067h,066h
        db 03Eh,013h,016h,05Ch,076h,033h,067h,07Eh,00Ch,01Ah,032h,020h,061h,062h,076h,03Ch
        db 03Ch,012h,011h,051h,071h,023h,07Eh,078h,023h,03Eh,010h,05Ch,070h,021h,067h,07Ch
        db 043h,07Eh,010h,052h,07Ch,024h,060h,070h,00Ch,01Ah,032h,020h,067h,062h,076h,03Ch
        db 031h,011h,012h,052h,07Eh,022h,06Eh,067h,006h,002h,004h,004h,02Ch,01Ch,018h,018h
        db 007h,002h,002h,046h,024h,064h,06Ch,038h,041h,031h,013h,026h,038h,06Eh,067h,063h
        db 018h,008h,010h,010h,030h,060h,07Fh,076h,061h,033h,015h,029h,02Ah,062h,067h,063h
        db 061h,031h,013h,02Ah,026h,062h,067h,063h,03Eh,013h,021h,021h,061h,062h,03Eh,018h
        db 06Eh,033h,011h,051h,072h,03Ch,060h,060h,00Eh,013h,021h,021h,065h,062h,07Fh,039h
        db 06Eh,033h,011h,053h,07Eh,028h,066h,063h,00Eh,013h,011h,04Ch,026h,063h,073h,03Eh
        db 067h,03Eh,010h,010h,030h,060h,060h,060h,063h,031h,011h,021h,021h,062h,07Eh,03Ch
        db 061h,031h,013h,022h,024h,068h,070h,060h,063h,021h,029h,069h,06Bh,07Ah,07Eh,034h
        db 031h,011h,00Ah,00Ch,03Ch,076h,067h,063h,031h,011h,01Ah,00Ch,00Ch,018h,018h,018h
        db 033h,01Eh,004h,008h,010h,071h,07Fh,066h,00Eh,008h,008h,008h,008h,008h,00Eh,000h
        db 000h,000h,080h,040h,020h,010h,008h,000h,070h,010h,010h,010h,010h,010h,070h,000h
        db 020h,050h,088h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,0F8h,000h
        db 040h,020h,010h,000h,000h,000h,000h,000h,000h,000h,070h,008h,078h,088h,078h,000h
        db 080h,080h,0B0h,0C8h,088h,0C8h,0B0h,000h,000h,000h,070h,088h,080h,088h,070h,000h
        db 008h,008h,068h,098h,088h,098h,068h,000h,000h,000h,070h,088h,0F8h,080h,070h,000h
        db 010h,028h,020h,0F8h,020h,020h,020h,000h,000h,000h,068h,098h,098h,068h,008h,070h
        db 080h,080h,0F0h,088h,088h,088h,088h,000h,020h,000h,060h,020h,020h,020h,070h,000h
        db 010h,000h,030h,010h,010h,010h,090h,060h,040h,040h,048h,050h,060h,050h,048h,000h
        db 060h,020h,020h,020h,020h,020h,070h,000h,000h,000h,0D0h,0A8h,0A8h,0A8h,0A8h,000h
        db 000h,000h,0B0h,0C8h,088h,088h,088h,000h,000h,000h,070h,088h,088h,088h,070h,000h
        db 000h,000h,0B0h,0C8h,0C8h,0B0h,080h,080h,000h,000h,068h,098h,098h,068h,008h,008h
        db 000h,000h,0B0h,0C8h,080h,080h,080h,000h,000h,000h,078h,080h,0F0h,008h,0F0h,000h
        db 040h,040h,0F0h,040h,040h,048h,030h,000h,000h,000h,090h,090h,090h,090h,068h,000h
        db 000h,000h,088h,088h,088h,050h,020h,000h,000h,000h,088h,0A8h,0A8h,0A8h,050h,000h
        db 000h,000h,088h,050h,020h,050h,088h,000h,000h,000h,088h,088h,098h,068h,008h,070h
        db 000h,000h,0F8h,010h,020h,040h,0F8h,000h,000h,000h,000h,000h,000h,000h,000h,000h

enemy_gfx:
        db 000h,00Fh,01Bh,015h,01Fh,00Fh,003h,00Fh,01Bh,033h,006h,00Ch,018h,038h,000h,000h
        db 000h,0F0h,0D8h,0A8h,0F8h,0F0h,0C0h,0F0h,0D8h,0CCh,060h,030h,018h,01Ch,000h,000h
        db 000h,00Fh,01Bh,015h,01Fh,00Fh,003h,00Fh,00Bh,00Bh,006h,006h,006h,00Eh,000h,000h
        db 000h,0F0h,0D8h,0A8h,0F8h,0F0h,0C0h,0F0h,0D0h,0D0h,060h,060h,060h,070h,000h,000h

bear_gfx:
        db 018h,018h,00Fh,00Fh,007h,03Ch,078h,03Fh,03Fh,01Fh,00Fh,00Eh,00Eh,01Eh,000h,000h
        db 018h,018h,0F0h,0F0h,0E0h,03Ch,01Eh,0FCh,0FCh,0F8h,0F0h,070h,070h,078h,000h,000h
        db 018h,018h,00Fh,00Fh,007h,00Fh,01Fh,03Fh,03Fh,01Fh,00Fh,01Ch,01Ch,00Fh,000h,000h
        db 018h,018h,0F0h,0F0h,0E0h,0F0h,0F8h,0FCh,0FCh,0F8h,0F0h,038h,038h,0F0h,000h,000h

chicken_gfx:
        db 001h,003h,007h,003h,00Fh,01Fh,03Fh,03Fh,03Fh,01Fh,00Fh,007h,007h,00Fh,000h,000h
        db 080h,0C0h,0E0h,0C0h,0F0h,0F8h,0FCh,0FCh,0FCh,0F8h,0F0h,070h,070h,0F8h,000h,000h
        db 001h,003h,007h,003h,00Fh,01Fh,03Fh,03Fh,03Fh,01Fh,00Fh,01Ch,01Ch,03Eh,000h,000h
        db 080h,0C0h,0E0h,0C0h,0F0h,0F8h,0FCh,0FCh,0FCh,0F8h,0F0h,038h,038h,07Ch,000h,000h

rat_gfx:
        db 00Ch,00Ch,007h,007h,00Fh,007h,01Fh,03Fh,03Fh,01Fh,01Ch,038h,0CEh,0E0h,070h,000h
        db 030h,030h,0E0h,0ECh,0DEh,0E0h,0F8h,0FCh,0FCh,0F8h,038h,01Ch,070h,000h,000h,000h
        db 00Ch,00Ch,007h,007h,00Fh,007h,01Fh,03Fh,03Fh,01Fh,038h,070h,0ECh,070h,0E0h,000h
        db 030h,030h,0E0h,0ECh,0DEh,0E0h,0F8h,0FCh,0FCh,0F8h,01Ch,00Eh,030h,000h,000h,000h

; room name strings for the intro card: raw ASCII, draw_string-ready
room1_name:
        db 67,69,78,84,82,65,76,32,67,65,86,69,82,78,0
room2_name:
        db 84,72,69,32,67,79,76,68,32,82,79,79,77,0
room3_name:
        db 84,72,69,32,77,69,78,65,71,69,82,73,69,0
room4_name:
        db 65,66,65,78,68,79,78,69,68,32,85,82,65,78,73,85,77,32,87,79,82,75,73,78,71,83,0

; room_tab: one row per room, read into room_state RAM struct
; via a single ldir at room_start. Field order/sizes MUST match
; the room_state RESB block in src/main.asm exactly.
ROOMROWLEN equ 39
room_tab:
        db 2,3
        dw level1_map
        dw keys_tab
        db 3
        dw keys_gfx
        dw slab_tab
        db 9
        db 2
        dw crumb_tab
        db 84
        dw hazards_tab
        db 3
        db 96,0,16
        db 25,12,2,32
        dw exit_gfx_0
        dw exit_gfx_1
        dw enemy_gfx
        db 3
        db 52,91,40,24
        dw room1_name
        db 85,86
        dw level2_map
        dw keys_tab2
        db 3
        dw keys_gfx2
        dw slab_tab2
        db 6
        db 2
        dw crumb_tab2
        db 87
        dw hazards_tab2
        db 2
        db 112,48,16
        db 21,16,2,32
        dw exit_gfx2_0
        dw exit_gfx2_1
        dw bear_gfx
        db 14
        db 92,124,56,16
        dw room2_name
        db 88,89
        dw level3_map
        dw keys_tab3
        db 3
        dw keys_gfx3
        dw slab_tab3
        db 5
        db 3
        dw crumb_tab3
        db 90
        dw hazards_tab3
        db 2
        db 96,64,16
        db 17,16,2,40
        dw exit_gfx3_0
        dw exit_gfx3_1
        dw chicken_gfx
        db 15
        db 48,96,40,32
        dw room3_name
        db 91,92
        dw level4_map
        dw keys_tab4
        db 3
        dw keys_gfx4
        dw slab_tab4
        db 4
        db 0
        dw crumb_tab4
        db 84
        dw hazards_tab4
        db 2
        db 96,64,16
        db 17,16,2,40
        dw exit_gfx4_0
        dw exit_gfx4_1
        dw rat_gfx
        db 13
        db 48,96,40,32
        dw room4_name

gfx_sprites:
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,010h,000h,000h,000h,000h,006h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,010h,000h,000h,000h,000h,0C0h
        db 000h,000h,005h,007h,002h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,040h,0C0h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 007h,00Fh,000h,000h,000h,00Fh,01Eh,01Dh,016h,017h,004h,007h,006h,006h,006h,000h
        db 0C0h,0E0h,000h,000h,000h,0E0h,070h,0F0h,0D0h,050h,0C0h,0C0h,0C0h,0C0h,0C0h,000h
        db 000h,000h,002h,000h,001h,000h,001h,002h,001h,000h,003h,000h,000h,000h,000h,000h
        db 000h,000h,080h,000h,000h,000h,080h,000h,000h,080h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,006h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,010h,000h,000h,000h,000h,000h
        db 000h,000h,005h,007h,002h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,040h,0C0h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 007h,00Fh,000h,000h,000h,00Fh,01Eh,01Dh,006h,007h,004h,007h,006h,006h,006h,000h
        db 0C0h,0E0h,000h,000h,000h,0E0h,070h,0F0h,0D0h,050h,0C0h,0C0h,0C0h,000h,000h,000h
        db 000h,000h,002h,000h,001h,000h,001h,002h,001h,000h,003h,000h,000h,000h,000h,000h
        db 000h,000h,080h,000h,000h,000h,080h,000h,000h,080h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,010h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,0C0h
        db 000h,000h,005h,007h,002h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,040h,0C0h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 007h,00Fh,000h,000h,000h,00Fh,01Eh,01Dh,016h,017h,004h,007h,006h,000h,000h,000h
        db 0C0h,0E0h,000h,000h,000h,0E0h,070h,0F0h,0C0h,040h,0C0h,0C0h,0C0h,0C0h,0C0h,000h
        db 000h,000h,002h,000h,001h,000h,001h,002h,001h,000h,003h,000h,000h,000h,000h,000h
        db 000h,000h,080h,000h,000h,000h,080h,000h,000h,080h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,010h,000h,000h,000h,000h,006h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,010h,000h,000h,000h,000h,0C0h
        db 000h,000h,007h,007h,003h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,0C0h,0C0h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 007h,00Fh,000h,000h,000h,00Fh,01Fh,01Fh,017h,017h,007h,007h,006h,006h,006h,000h
        db 0C0h,0E0h,000h,000h,000h,0E0h,0F0h,0F0h,0D0h,0D0h,0C0h,0C0h,0C0h,0C0h,0C0h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,006h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,010h,000h,000h,000h,000h,000h
        db 000h,000h,007h,007h,003h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,0C0h,0C0h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 007h,00Fh,000h,000h,000h,00Fh,01Fh,01Fh,007h,007h,007h,007h,006h,006h,006h,000h
        db 0C0h,0E0h,000h,000h,000h,0E0h,0F0h,0F0h,0D0h,0D0h,0C0h,0C0h,0C0h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,010h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,0C0h
        db 000h,000h,007h,007h,003h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,0C0h,0C0h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 007h,00Fh,000h,000h,000h,00Fh,01Fh,01Fh,017h,017h,007h,007h,006h,000h,000h,000h
        db 0C0h,0E0h,000h,000h,000h,0E0h,0F0h,0F0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,001h,000h,000h,000h,000h,000h,003h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,080h
        db 000h,000h,002h,003h,001h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,0C0h,0C0h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 003h,007h,001h,000h,000h,001h,003h,003h,003h,002h,003h,001h,001h,001h,001h,000h
        db 0C0h,0E0h,000h,000h,000h,080h,0C0h,0C0h,0C0h,0C0h,0C0h,080h,080h,080h,080h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,002h,000h,000h,000h,000h,010h,030h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,040h,040h,000h
        db 000h,000h,00Bh,00Fh,006h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 00Fh,01Fh,000h,000h,000h,006h,00Fh,00Fh,00Fh,00Dh,00Fh,00Fh,01Bh,010h,000h,000h
        db 000h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,080h,080h,000h,000h
        db 000h,000h,004h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,004h,000h,000h,000h,000h,000h,006h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,080h,080h,000h
        db 000h,000h,00Bh,00Fh,006h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 00Fh,01Fh,000h,000h,000h,006h,00Fh,00Fh,00Fh,00Bh,00Fh,00Fh,005h,007h,002h,000h
        db 000h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,004h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,001h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,080h,000h,000h,000h,000h,000h,0C0h
        db 000h,000h,003h,003h,001h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,040h,0C0h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 003h,007h,000h,000h,000h,001h,003h,003h,003h,003h,003h,001h,001h,001h,001h,000h
        db 0C0h,0E0h,000h,000h,000h,080h,0C0h,0C0h,0C0h,040h,0C0h,080h,080h,080h,080h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,080h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,002h,002h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,040h,000h,000h,000h,000h,008h,00Ch
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,0D0h,0F0h,060h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,001h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,001h,001h,000h,000h
        db 0F0h,0F8h,000h,000h,000h,060h,0F0h,0F0h,0F0h,0B0h,0F0h,0F0h,0D8h,008h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,020h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,001h,001h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,020h,000h,000h,000h,000h,000h,060h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,0D0h,0F0h,060h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,001h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 0F0h,0F8h,000h,000h,000h,060h,0F0h,0F0h,0F0h,0D0h,0F0h,0F0h,0A0h,0E0h,040h,000h
        db 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
        db 000h,000h,020h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
